
* CANCELED build ive environment on another pc
  - State "CANCELED"   from "IN-PROGRESS" [2018-11-02 Fri 14:02] \\
    don't need for now
  - State "IN-PROGRESS" from "TODO"       [2018-10-26 Fri 16:18] \\
    boost is ok, but opencv has make issue
  - State "TODO"       from              [2018-10-25 Thu 17:34] \\
    set up ive, test prediction time
* DONE test rgb time
  - State "DONE"       from "TODO"       [2018-10-29 Mon 15:03] \\
    time is 0.6 ms per image
  - State "TODO"       from              [2018-10-29 Mon 10:59] \\
    test Dollar rgb time
* CANCELED add r,g,b to mnist samples
  - State "CANCELED"   from "UPDATE"     [2018-11-06 Tue 15:08] \\
    rgb bin file was not supported by camera, so no need.
  - State "UPDATE"     from "DONE"       [2018-11-05 Mon 13:02] \\
    wrong extention
  - State "DONE"       from "IN-PROGRESS" [2018-11-02 Fri 14:02] \\
    done
  - State "IN-PROGRESS" from "TODO"       [2018-10-29 Mon 15:13] \\
    if [0,0,0], replace with 
    [255,0,0] - r
    [0,255,0] - g
    [0,0,255] - b
  - State "TODO"       from              [2018-10-29 Mon 11:01] \\
    turn mnist samples to rgb images, extend categories like red0, green0, blue0. Then, test accuracy and time.
* DONE test rgb bin file on camera
  - State "DONE"       from "DONE"       [2018-11-06 Tue 15:18] \\
    model bin file is generated by modified network file, and it successfully accepted by ive_tool, but doesn't accept by camera.
  - State "DONE"       from "IN-PROGRESS" [2018-11-06 Tue 15:04] \\
    cannot run rgb yuv on camera, not support. HI_MPI_IVE_CNN_Predict() failed,Error(0xa01d8003), this function is in mpi_ive.h, relevant source code is in lib/libive.so or lib/libive.a.
    don't have source code of these two lib file, so cannot modify them.
  - State "IN-PROGRESS" from "TODO"       [2018-10-29 Mon 15:04] \\
    no source code, cannot test with bin file in camera
  - State "TODO"       from              [2018-10-29 Mon 11:11] \\
    after solving nfs issue, validate rgb bin file
* DONE learn HOG algorithm in OpenCV
  - State "DONE"       from "DONE"       [2018-11-09 Fri 16:37] \\
    don't need HOG in OpenCV, customized one
  - State "IN-PROGRESS" from "IN-PROGRESS" [2018-11-08 Thu 17:14] \\
    convert magtitude and angle of gradient vector from image into 1x8 array
  - State "IN-PROGRESS" from "IN-PROGRESS" [2018-11-08 Thu 10:14] \\
    HOG in opencv doesn't coordinate with the algorithm in camera
  - State "IN-PROGRESS" from              [2018-11-06 Tue 14:17] \\
    learned HOG and relevant things, next step is to apply to svm
* DONE HOG&SVM to detect plate frame
  - State "DONE"       from "IN-PROGRESS" [2018-11-09 Fri 16:37] \\
    extend 1d mat to img.rows * img.cols, but performance is very bad(<0.4)
  - State "IN-PROGRESS" from              [2018-11-06 Tue 15:08] \\
    need samples of plates
