
* IN-PROGRESS test rgb bin file on camera
  - State "IN-PROGRESS" from "DONE"       [2018-11-12 Mon 16:11] \\
    change input type in sample_ive_cnn.c from 8UC1 to YUV420P, still doesn't work. you can search "YUV420P" in sample_ive_cnn.c to locate it.
  - State "DONE"       from "DONE"       [2018-11-06 Tue 15:18] \\
    model bin file is generated by modified network file, and it successfully accepted by ive_tool, but doesn't accept by camera.
  - State "DONE"       from "IN-PROGRESS" [2018-11-06 Tue 15:04] \\
    cannot run rgb yuv on camera, not support. HI_MPI_IVE_CNN_Predict() failed,Error(0xa01d8003), this function is in mpi_ive.h, relevant source code is in lib/libive.so or lib/libive.a.
    don't have source code of these two lib file, so cannot modify them.
  - State "IN-PROGRESS" from "TODO"       [2018-10-29 Mon 15:04] \\
    no source code, cannot test with bin file in camera
  - State "TODO"       from              [2018-10-29 Mon 11:11] \\
    after solving nfs issue, validate rgb bin file
* DONE change input dim of svm to 1x8 mat
  - State "DONE"       from "IN-PROGRESS" [2018-11-19 Mon 14:30] \\
    solve data type issue
  - State "IN-PROGRESS" from              [2018-11-12 Mon 16:14] \\
    default is 1x(width*height)
* DONE correct xml file
  - State "DONE"       from "IN-PROGRESS" [2018-11-19 Mon 14:31] \\
    svmType -> svm_type
    copy var_cout -> var_all
  - State "IN-PROGRESS" from              [2018-11-12 Mon 16:25] \\
    modify svmType to svm_type in xml file, and it works, but prompt "var exceed [1,1024]"
* DONE crop (h or v)lines, curves on car image
  - State "DONE"       from "IN-PROGRESS" [2018-11-19 Mon 14:31] \\
    crop 32x32 patches, and generate 1x8
  - State "IN-PROGRESS" from              [2018-11-13 Tue 16:02] \\
    after receive car imagees, use HOG to extract edge features, and then crop the basic features like lines curves
