
* DEFER test rgb bin file on camera
  - State "DEFER"      from "IN-PROGRESS" [2018-11-19 Mon 14:41] \\
    after corrected file type, still has the issue.
  - State "IN-PROGRESS" from "DONE"       [2018-11-12 Mon 16:11] \\
    change input type in sample_ive_cnn.c from 8UC1 to YUV420P, still doesn't work. you can search "YUV420P" in sample_ive_cnn.c to locate it.
  - State "DONE"       from "DONE"       [2018-11-06 Tue 15:18] \\
    model bin file is generated by modified network file, and it successfully accepted by ive_tool, but doesn't accept by camera.
  - State "DONE"       from "IN-PROGRESS" [2018-11-06 Tue 15:04] \\
    cannot run rgb yuv on camera, not support. HI_MPI_IVE_CNN_Predict() failed,Error(0xa01d8003), this function is in mpi_ive.h, relevant source code is in lib/libive.so or lib/libive.a.
    don't have source code of these two lib file, so cannot modify them.
  - State "IN-PROGRESS" from "TODO"       [2018-10-29 Mon 15:04] \\
    no source code, cannot test with bin file in camera
  - State "TODO"       from              [2018-10-29 Mon 11:11] \\
    after solving nfs issue, validate rgb bin file
* DONE run svm bin file on camera
  - State "DONE"       from              [2018-11-19 Mon 14:35] \\
    it works, but all predicted categories are wrong. Tried original reshape(1, 1) working well on PC cannot be predicted on camera, all are predicted as "Class 1"
* DONE select valid 32x32 patches
  - State "DONE"       from "IN-PROGRESS" [2018-11-28 Wed 09:41] \\
    done
  - State "IN-PROGRESS" from "IN-PROGRESS" [2018-11-23 Fri 14:13] \\
    Ubuntu is down, and cannot resume, so reinstall Ubuntu and rebuild all environment
  - State "IN-PROGRESS" from              [2018-11-19 Mon 14:37] \\
    crop rgb image first, keep same filename, select rgb images, and update with 1x8 images.
* IN-PROGRESS correct svm params according to hi API
  - State "IN-PROGRESS" from "IN-PROGRESS" [2018-11-28 Wed 09:42] \\
    after sorting out 32x32 samples, predicting accuracy is very low
  - State "IN-PROGRESS" from              [2018-11-19 Mon 14:42] \\
    start to learn relevant hi API
