
* DEFER test rgb bin file on camera
  - State "DEFER"      from "IN-PROGRESS" [2018-11-19 Mon 14:41] \\
    after corrected file type, still has the issue.
  - State "IN-PROGRESS" from "DONE"       [2018-11-12 Mon 16:11] \\
    change input type in sample_ive_cnn.c from 8UC1 to YUV420P, still doesn't work. you can search "YUV420P" in sample_ive_cnn.c to locate it.
  - State "DONE"       from "DONE"       [2018-11-06 Tue 15:18] \\
    model bin file is generated by modified network file, and it successfully accepted by ive_tool, but doesn't accept by camera.
  - State "DONE"       from "IN-PROGRESS" [2018-11-06 Tue 15:04] \\
    cannot run rgb yuv on camera, not support. HI_MPI_IVE_CNN_Predict() failed,Error(0xa01d8003), this function is in mpi_ive.h, relevant source code is in lib/libive.so or lib/libive.a.
    don't have source code of these two lib file, so cannot modify them.
  - State "IN-PROGRESS" from "TODO"       [2018-10-29 Mon 15:04] \\
    no source code, cannot test with bin file in camera
  - State "TODO"       from              [2018-10-29 Mon 11:11] \\
    after solving nfs issue, validate rgb bin file
* IN-PROGRESS correct svm params according to hi API
  - State "IN-PROGRESS" from "IN-PROGRESS" [2018-11-28 Wed 09:42] \\
    after sorting out 32x32 samples, predicting accuracy is very low
  - State "IN-PROGRESS" from              [2018-11-19 Mon 14:42] \\
    start to learn relevant hi API
* DONE rebuild samples
  - State "DONE"       from "IN-PROGRESS" [2018-12-03 Mon 12:59] \\
    accuracy 0.6, 0.7.
    move 50 0s and 50 1s from test to train, accuracy descned to 0.3, 0.4
  - State "IN-PROGRESS" from              [2018-11-29 Thu 12:40] \\
    categories: plate, non-plate
    size: 48x16
